# Generated by Django 5.0 on 2024-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_created_at_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='employees'),
        ),
    ]
