# Generated by Django 5.0 on 2024-01-06 14:58

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_employee_profile_pic_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='employees/employee.png', null=True, upload_to=main_app.models.unique_img_name),
        ),
    ]
